### PR TITLE
Feature/display cover image in maintable

### PR DESCRIPTION
**Pull request by thanhnl2004**
Our team has made some changes to implement the required features, currently here is what we have done so far regarding issue [#10120](https://github.com/JabRef/jabref/issues/10120)
- Created a resizable `SplitPane` to hold the book cover.
- Added functionalities to load images from local computer to the book cover, with the "cover" description being the first priority for JabRef to choose which book cover to choose from if an entry has multiple image files. (A default image is loaded if no images are provided)
Please review and run JabRef to check if the behaviours match what I have described above.

### CODE REVIEW

**Review by Naaeeen — APPROVED** [review]
Hey team, I noticed two errors during the build:

Architecture Rule Violation
In MainArchitectureTest, the method showBookCover in LibraryTab.java is calling Class.getResource(...), which violates the architecture rule. It’s recommended to use getResourceAsStream(...) instead.


Unused Images in IconsPropertiesTest
The existenceOfIconImagesReferencedFromIconsProperties test failed. The test expected only red.png to be present, but it found both default_image.png and red.png. If default_image.png isn’t needed, we should remove it; otherwise, the test logic might need adjusting.
Also, there’s a checkstyle violation that caused the build to fail.

These two shouldn't be a big deal. Just give them a quick check before merging :)

**Comment by thanhnl2004** [comment]
> Hey team, I noticed two errors during the build:
> 
> Architecture Rule Violation In MainArchitectureTest, the method showBookCover in LibraryTab.java is calling Class.getResource(...), which violates the architecture rule. It’s recommended to use getResourceAsStream(...) instead.
> 
> Unused Images in IconsPropertiesTest The existenceOfIconImagesReferencedFromIconsProperties test failed. The test expected only red.png to be present, but it found both default_image.png and red.png. If default_image.png isn’t needed, we should remove it; otherwise, the test logic might need adjusting. Also, there’s a checkstyle violation that caused the build to fail.
> 
> These two shouldn't be a big deal. Just give them a quick check before merging :)

If I changed to `getResourceAsStream(...)`, the code couldn't load the local images for some reasons. And yes, we did use `default_image.png` to load a default image for every entry in case the user doesn't provide any local images.

**Comment by BruceLiang1234** [comment]
Besides what Naaeeen talked about, everything else looks good to me. From your explaination the fail of first test seems ok, but for The existenceOfIconImagesReferencedFromIconsProperties test you may want to change the testing logic or the behaviour of the code to pass the test. And maybe you want to double check the code style that has been reported.

**Review by BruceLiang1234 — APPROVED** [review]

**Comment by u7465990** [comment]
It's a great progress on the feature, but there are some checkstyle violations related to the Javadoc comments. Fixing these minor formatting issues should  allow the build to pass successfully.

**Review by u7465990 — APPROVED** [review]

**Pull request merged**
